name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Local Binary
      run: cargo build --release --verbose
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Build WebAssembly Module and Generate JavaScript
      run: wasm-pack build --target web
    - name: Rust Format Check
      run: cargo fmt -- --check
